INSERT INTO `key_values` (`table_name`, `column_name`, `key_value`) VALUES
  ('participant' , 'gregor_center' , 'BCM'),
  ('participant' , 'gregor_center' , 'BROAD'),
  ('participant' , 'gregor_center' , 'CNH_I'),
  ('participant' , 'gregor_center' , 'UCI'),
  ('participant' , 'gregor_center' , 'UW_CRDR'),
  ('participant' , 'gregor_center' , 'GSS'),
  ('participant' , 'gregor_center' , 'UW_DCC'),
  ('participant' , 'gregor_center' , 'ILMN-IHOPE'),
  ('participant' , 'consent_code' , 'GRU'),
  ('participant' , 'consent_code' , 'HMB'),
  ('participant' , 'recontactable' , 'Yes'),
  ('participant' , 'recontactable' , 'No'),
  ('participant' , 'proband_relationship' , 'Self'),
  ('participant' , 'proband_relationship' , 'Mother'),
  ('participant' , 'proband_relationship' , 'Father'),
  ('participant' , 'proband_relationship' , 'Sibling'),
  ('participant' , 'proband_relationship' , 'Child'),
  ('participant' , 'proband_relationship' , 'Maternal Half Sibling'),
  ('participant' , 'proband_relationship' , 'Paternal Half Sibling'),
  ('participant' , 'proband_relationship' , 'Maternal Grandmother'),
  ('participant' , 'proband_relationship' , 'Maternal Grandfather'),
  ('participant' , 'proband_relationship' , 'Paternal Grandmother'),
  ('participant' , 'proband_relationship' , 'Paternal Grandfather'),
  ('participant' , 'proband_relationship' , 'Maternal Aunt'),
  ('participant' , 'proband_relationship' , 'Maternal Uncle'),
  ('participant' , 'proband_relationship' , 'Paternal Aunt'),
  ('participant' , 'proband_relationship' , 'Paternal Uncle'),
  ('participant' , 'proband_relationship' , 'Niece'),
  ('participant' , 'proband_relationship' , 'Nephew'),
  ('participant' , 'proband_relationship' , 'Maternal 1st Cousin'),
  ('participant' , 'proband_relationship' , 'Paternal 1st Cousin'),
  ('participant' , 'proband_relationship' , 'Other'),
  ('participant' , 'proband_relationship' , 'Unknown'),
  ('participant' , 'sex' , 'Female'),
  ('participant' , 'sex' , 'Male'),
  ('participant' , 'sex' , 'Unknown'),
  ('participant' , 'reported_race' , 'American Indian or Alaska Native'),
  ('participant' , 'reported_race' , 'Asian'),
  ('participant' , 'reported_race' , 'Black or African American'),
  ('participant' , 'reported_race' , 'Native Hawaiian or Other Pacific Islander'),
  ('participant' , 'reported_race' , 'Middle Eastern or North African'),
  ('participant' , 'reported_race' , 'White'),
  ('participant' , 'reported_ethnicity' , 'Hispanic or Latino'),
  ('participant' , 'reported_ethnicity' , 'Not Hispanic or Latino'),
  ('participant' , 'affected_status' , 'Affected'),
  ('participant' , 'affected_status' , 'Unaffected'),
  ('participant' , 'affected_status' , 'Possibly affected'),
  ('participant' , 'affected_status' , 'Unknown'),
  ('participant' , 'solve_status' , 'Solved'),
  ('participant' , 'solve_status' , 'Partially solved'),
  ('participant' , 'solve_status' , 'Probably solved'),
  ('participant' , 'solve_status' , 'Unsolved'),
  ('participant' , 'solve_status' , 'Unaffected'),
  ('participant' , 'missing_variant_case' , 'Yes'),
  ('participant' , 'missing_variant_case' , 'No'),
  ('participant' , 'missing_variant_case' , 'Unknown'),
  ('family' , 'consanguinity' , 'None suspected'),
  ('family' , 'consanguinity' , 'Suspected'),
  ('family' , 'consanguinity' , 'Present'),
  ('family' , 'consanguinity' , 'Unknown'),
  ('phenotype' , 'presence' , 'Present'),
  ('phenotype' , 'presence' , 'Absent'),
  ('phenotype' , 'presence' , 'Unknown'),
  ('phenotype' , 'ontology' , 'HPO'),
  ('phenotype' , 'ontology' , 'MONDO'),
  ('phenotype' , 'ontology' , 'OMIM'),
  ('phenotype' , 'ontology' , 'ORPHANET'),
  ('phenotype' , 'ontology' , 'SNOMED'),
  ('phenotype' , 'ontology' , 'ICD10'),
  ('phenotype' , 'onset_age_range' , 'HP:0003581'),
  ('phenotype' , 'onset_age_range' , 'HP:0030674'),
  ('phenotype' , 'onset_age_range' , 'HP:0011463'),
  ('phenotype' , 'onset_age_range' , 'HP:0003577'),
  ('phenotype' , 'onset_age_range' , 'HP:0025708'),
  ('phenotype' , 'onset_age_range' , 'HP:0011460'),
  ('phenotype' , 'onset_age_range' , 'HP:0011461'),
  ('phenotype' , 'onset_age_range' , 'HP:0003593'),
  ('phenotype' , 'onset_age_range' , 'HP:0025709'),
  ('phenotype' , 'onset_age_range' , 'HP:0003621'),
  ('phenotype' , 'onset_age_range' , 'HP:0034199'),
  ('phenotype' , 'onset_age_range' , 'HP:0003584'),
  ('phenotype' , 'onset_age_range' , 'HP:0025710'),
  ('phenotype' , 'onset_age_range' , 'HP:0003596'),
  ('phenotype' , 'onset_age_range' , 'HP:0003623'),
  ('phenotype' , 'onset_age_range' , 'HP:0410280'),
  ('phenotype' , 'onset_age_range' , 'HP:4000040'),
  ('phenotype' , 'onset_age_range' , 'HP:0034198'),
  ('phenotype' , 'onset_age_range' , 'HP:0034197'),
  ('phenotype' , 'onset_age_range' , 'HP:0011462'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025292'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011009'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025308'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025307'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025306'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003581'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011420'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003831'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025285'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032525'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025286'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025254'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032526'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025257'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032503'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025256'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032522'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025255'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030674'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033820'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000052'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025287'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012832'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012827'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033815'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030645'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033816'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032535'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011463'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011010'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031797'),
  ('phenotype' , 'additional_modifiers' , 'HP:0045088'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000051'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000048'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000047'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003577'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011421'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033763'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003819'),
  ('phenotype' , 'additional_modifiers' , 'HP:0100613'),
  ('phenotype' , 'additional_modifiers' , 'HP:0001522'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033765'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033764'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025294'),
  ('phenotype' , 'additional_modifiers' , 'HP:0020034'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000053'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012839'),
  ('phenotype' , 'additional_modifiers' , 'HP:0045089'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025293'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025302'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025282'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025708'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011460'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025303'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032365'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032502'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032501'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025315'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032534'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032542'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032500'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011461'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031914'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030650'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000042'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012837'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000043'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025295'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003829'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003593'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003587'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025709'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032539'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032540'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003621'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034199'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003584'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025710'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025275'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012831'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012835'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012838'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025291'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003596'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030648'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025279'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012825'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033817'),
  ('phenotype' , 'additional_modifiers' , 'HP:0045090'),
  ('phenotype' , 'additional_modifiers' , 'HP:0005268'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012826'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025296'),
  ('phenotype' , 'additional_modifiers' , 'HP:0040006'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030651'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003811'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003623'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025301'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003680'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000046'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003674'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000050'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003679'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025280'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030647'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033814'),
  ('phenotype' , 'additional_modifiers' , 'HP:0410280'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030649'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033813'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033819'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025304'),
  ('phenotype' , 'additional_modifiers' , 'HP:0030646'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003812'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031450'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012830'),
  ('phenotype' , 'additional_modifiers' , 'HP:0032544'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034241'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012829'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003676'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025297'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012840'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000040'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025305'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003678'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031796'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031375'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033818'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012834'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034198'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000049'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033349'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012828'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012824'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025281'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025284'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003677'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012836'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000045'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031915'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003826'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011011'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011008'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025283'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034197'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025153'),
  ('phenotype' , 'additional_modifiers' , 'HP:4000044'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025204'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033185'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033032'),
  ('phenotype' , 'additional_modifiers' , 'HP:0500261'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025205'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025208'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033789'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025206'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025207'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025334'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025211'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025227'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025377'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025212'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034060'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025215'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033793'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025209'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025213'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025210'),
  ('phenotype' , 'additional_modifiers' , 'HP:0500260'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025214'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025216'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025217'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025218'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033184'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031167'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025220'),
  ('phenotype' , 'additional_modifiers' , 'HP:0034195'),
  ('phenotype' , 'additional_modifiers' , 'HP:0031135'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025221'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025222'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025223'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025224'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025225'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025226'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025228'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025219'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025229'),
  ('phenotype' , 'additional_modifiers' , 'HP:0033198'),
  ('phenotype' , 'additional_modifiers' , 'HP:0012833'),
  ('phenotype' , 'additional_modifiers' , 'HP:0025290'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003828'),
  ('phenotype' , 'additional_modifiers' , 'HP:0003682'),
  ('phenotype' , 'additional_modifiers' , 'HP:0410401'),
  ('phenotype' , 'additional_modifiers' , 'HP:0011462'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021125'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021135'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021139'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021149'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0045034'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0045040'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100355'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700004'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100369'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700061'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024488'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021126'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021136'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021137'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021140'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021141'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021151'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021152'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0045036'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0045035'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0022202'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0045042'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100356'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100357'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700005'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700006'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100427'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0100426'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700063'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0700062'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024489'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021128'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0021127'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024497'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024495'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024490'),
  ('phenotype' , 'additional_modifiers' , 'MONDO:0024496'),
  ('phenotype' , 'syndromic' , 'syndromic'),
  ('phenotype' , 'syndromic' , 'non-syndromic'),
  ('genetic_findings' , 'variant_type' , 'SNV'),
  ('genetic_findings' , 'variant_type' , 'INDEL'),
  ('genetic_findings' , 'variant_type' , 'SV'),
  ('genetic_findings' , 'variant_type' , 'RE'),
  ('genetic_findings' , 'sv_type' , 'BND'),
  ('genetic_findings' , 'sv_type' , 'CNV'),
  ('genetic_findings' , 'sv_type' , 'CPX'),
  ('genetic_findings' , 'sv_type' , 'CTX'),
  ('genetic_findings' , 'sv_type' , 'DEL'),
  ('genetic_findings' , 'sv_type' , 'DUP'),
  ('genetic_findings' , 'sv_type' , 'INS'),
  ('genetic_findings' , 'sv_type' , 'INS:ME'),
  ('genetic_findings' , 'sv_type' , 'INS:ME:ALU'),
  ('genetic_findings' , 'sv_type' , 'INS:ME:LINE1'),
  ('genetic_findings' , 'sv_type' , 'INS:ME:SVA'),
  ('genetic_findings' , 'sv_type' , 'INS:UNK'),
  ('genetic_findings' , 'sv_type' , 'INV'),
  ('genetic_findings' , 'variant_reference_assembly' , 'GRCh38'),
  ('genetic_findings' , 'variant_reference_assembly' , 'CHM13'),
  ('genetic_findings' , 'chrom' , '1'),
  ('genetic_findings' , 'chrom' , '2'),
  ('genetic_findings' , 'chrom' , '3'),
  ('genetic_findings' , 'chrom' , '4'),
  ('genetic_findings' , 'chrom' , '5'),
  ('genetic_findings' , 'chrom' , '6'),
  ('genetic_findings' , 'chrom' , '7'),
  ('genetic_findings' , 'chrom' , '8'),
  ('genetic_findings' , 'chrom' , '9'),
  ('genetic_findings' , 'chrom' , '10'),
  ('genetic_findings' , 'chrom' , '11'),
  ('genetic_findings' , 'chrom' , '12'),
  ('genetic_findings' , 'chrom' , '13'),
  ('genetic_findings' , 'chrom' , '14'),
  ('genetic_findings' , 'chrom' , '15'),
  ('genetic_findings' , 'chrom' , '16'),
  ('genetic_findings' , 'chrom' , '17'),
  ('genetic_findings' , 'chrom' , '18'),
  ('genetic_findings' , 'chrom' , '19'),
  ('genetic_findings' , 'chrom' , '20'),
  ('genetic_findings' , 'chrom' , '21'),
  ('genetic_findings' , 'chrom' , '22'),
  ('genetic_findings' , 'chrom' , 'X'),
  ('genetic_findings' , 'chrom' , 'Y'),
  ('genetic_findings' , 'chrom' , 'MT'),
  ('genetic_findings' , 'chrom_end' , '1'),
  ('genetic_findings' , 'chrom_end' , '2'),
  ('genetic_findings' , 'chrom_end' , '3'),
  ('genetic_findings' , 'chrom_end' , '4'),
  ('genetic_findings' , 'chrom_end' , '5'),
  ('genetic_findings' , 'chrom_end' , '6'),
  ('genetic_findings' , 'chrom_end' , '7'),
  ('genetic_findings' , 'chrom_end' , '8'),
  ('genetic_findings' , 'chrom_end' , '9'),
  ('genetic_findings' , 'chrom_end' , '10'),
  ('genetic_findings' , 'chrom_end' , '11'),
  ('genetic_findings' , 'chrom_end' , '12'),
  ('genetic_findings' , 'chrom_end' , '13'),
  ('genetic_findings' , 'chrom_end' , '14'),
  ('genetic_findings' , 'chrom_end' , '15'),
  ('genetic_findings' , 'chrom_end' , '16'),
  ('genetic_findings' , 'chrom_end' , '17'),
  ('genetic_findings' , 'chrom_end' , '18'),
  ('genetic_findings' , 'chrom_end' , '19'),
  ('genetic_findings' , 'chrom_end' , '20'),
  ('genetic_findings' , 'chrom_end' , '21'),
  ('genetic_findings' , 'chrom_end' , '22'),
  ('genetic_findings' , 'chrom_end' , 'X'),
  ('genetic_findings' , 'chrom_end' , 'Y'),
  ('genetic_findings' , 'chrom_end' , 'MT'),
  ('genetic_findings' , 'zygosity' , 'Heterozygous'),
  ('genetic_findings' , 'zygosity' , 'Homozygous'),
  ('genetic_findings' , 'zygosity' , 'Hemizygous'),
  ('genetic_findings' , 'zygosity' , 'Heteroplasmy'),
  ('genetic_findings' , 'zygosity' , 'Homoplasmy'),
  ('genetic_findings' , 'zygosity' , 'Mosaic'),
  ('genetic_findings' , 'zygosity' , 'Unknown'),
  ('genetic_findings' , 'variant_inheritance' , 'de novo'),
  ('genetic_findings' , 'variant_inheritance' , 'maternal'),
  ('genetic_findings' , 'variant_inheritance' , 'paternal'),
  ('genetic_findings' , 'variant_inheritance' , 'biparental'),
  ('genetic_findings' , 'variant_inheritance' , 'nonmaternal'),
  ('genetic_findings' , 'variant_inheritance' , 'nonpaternal'),
  ('genetic_findings' , 'variant_inheritance' , 'unknown'),
  ('genetic_findings' , 'linked_variant_phase' , 'in trans'),
  ('genetic_findings' , 'linked_variant_phase' , 'in cis'),
  ('genetic_findings' , 'linked_variant_phase' , 'unknown'),
  ('genetic_findings' , 'gene_known_for_phenotype' , 'Known'),
  ('genetic_findings' , 'gene_known_for_phenotype' , 'Candidate'),
  ('genetic_findings' , 'condition_inheritance' , 'Autosomal recessive'),
  ('genetic_findings' , 'condition_inheritance' , 'Autosomal dominant'),
  ('genetic_findings' , 'condition_inheritance' , 'X-linked'),
  ('genetic_findings' , 'condition_inheritance' , 'Mitochondrial'),
  ('genetic_findings' , 'condition_inheritance' , 'Y-linked'),
  ('genetic_findings' , 'condition_inheritance' , 'Contiguous gene syndrome'),
  ('genetic_findings' , 'condition_inheritance' , 'Somatic mosaicism'),
  ('genetic_findings' , 'condition_inheritance' , 'Digenic'),
  ('genetic_findings' , 'condition_inheritance' , 'Other'),
  ('genetic_findings' , 'condition_inheritance' , 'Unknown'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Benign'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Likely benign'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Uncertain significance - low'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Uncertain significance - moderate'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Uncertain significance - high'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Uncertain significance'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Likely pathogenic'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Pathogenic'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Curation in progress'),
  ('genetic_findings' , 'GREGoR_variant_classification' , 'Well-established P/LP'),
  ('genetic_findings' , 'gene_disease_validity' , 'Definitive'),
  ('genetic_findings' , 'gene_disease_validity' , 'Strong'),
  ('genetic_findings' , 'gene_disease_validity' , 'Moderate'),
  ('genetic_findings' , 'gene_disease_validity' , 'Limited'),
  ('genetic_findings' , 'gene_disease_validity' , 'Disputed'),
  ('genetic_findings' , 'gene_disease_validity' , 'Animal Model Only'),
  ('genetic_findings' , 'gene_disease_validity' , 'Refuted'),
  ('genetic_findings' , 'gene_disease_validity' , 'Curation in progress'),
  ('genetic_findings' , 'phenotype_contribution' , 'Partial'),
  ('genetic_findings' , 'phenotype_contribution' , 'Full'),
  ('genetic_findings' , 'phenotype_contribution' , 'Uncertain'),
  ('genetic_findings' , 'method_of_discovery' , 'SR-ES'),
  ('genetic_findings' , 'method_of_discovery' , 'SR-GS'),
  ('genetic_findings' , 'method_of_discovery' , 'LR-GS'),
  ('genetic_findings' , 'method_of_discovery' , 'SNP array'),
  ('genetic_findings' , 'method_of_discovery' , 'Optical mapping'),
  ('genetic_findings' , 'method_of_discovery' , 'Karyotype'),
  ('genetic_findings' , 'method_of_discovery' , 'SR RNA-seq'),
  ('genetic_findings' , 'method_of_discovery' , 'LR RNA-seq'),
  ('genetic_findings' , 'method_of_discovery' , 'SR-ES-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'SR-GS-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'LR-GS-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'SNP array-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'Optical mapping-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'Karyotype-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'SR RNA-seq-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'LR RNA-seq-reanalysis'),
  ('genetic_findings' , 'method_of_discovery' , 'Gene panel'),
  ('analyte' , 'analyte_type' , 'DNA'),
  ('analyte' , 'analyte_type' , 'RNA'),
  ('analyte' , 'analyte_type' , 'cDNA'),
  ('analyte' , 'analyte_type' , 'blood plasma'),
  ('analyte' , 'analyte_type' , 'frozen whole blood'),
  ('analyte' , 'analyte_type' , 'high molecular weight DNA'),
  ('analyte' , 'analyte_type' , 'urine'),
  ('analyte' , 'analyte_type' , 'PBMC'),
  ('analyte' , 'primary_biosample' , 'UBERON:0000479'),
  ('analyte' , 'primary_biosample' , 'UBERON:0003714'),
  ('analyte' , 'primary_biosample' , 'UBERON:0001836'),
  ('analyte' , 'primary_biosample' , 'UBERON:0001003'),
  ('analyte' , 'primary_biosample' , 'UBERON:0002385'),
  ('analyte' , 'primary_biosample' , 'UBERON:0000178'),
  ('analyte' , 'primary_biosample' , 'UBERON:0002371'),
  ('analyte' , 'primary_biosample' , 'UBERON:0006956'),
  ('analyte' , 'primary_biosample' , 'UBERON:0001359'),
  ('analyte' , 'primary_biosample' , 'UBERON:0001088'),
  ('analyte' , 'primary_biosample' , 'UBERON:0019306'),
  ('analyte' , 'primary_biosample' , 'CL: 0000034'),
  ('analyte' , 'primary_biosample' , 'CL: 0000576'),
  ('analyte' , 'primary_biosample' , 'CL: 0000542'),
  ('analyte' , 'primary_biosample' , 'CL: 0000057'),
  ('analyte' , 'primary_biosample' , 'UBERON:0005291'),
  ('analyte' , 'primary_biosample' , 'CL: 0011020'),
  ('analyte' , 'primary_biosample' , 'UBERON:0002037'),
  ('analyte' , 'primary_biosample' , 'UBERON:0001133'),
  ('analyte' , 'tissue_affected_status' , 'Yes'),
  ('analyte' , 'tissue_affected_status' , 'No'),
  ('experiment' , 'table_name' , 'experiment_dna_short_read'),
  ('experiment' , 'table_name' , 'experiment_rna_short_read'),
  ('experiment' , 'table_name' , 'experiment_nanopore'),
  ('experiment' , 'table_name' , 'experiment_pac_bio'),
  ('experiment' , 'table_name' , 'experiment_atac_short_read'),
  ('experiment' , 'table_name' , 'experiment_optical_mapping'),
  ('experiment' , 'table_name' , 'experiment_iclr'),
  ('aligned' , 'table_name' , 'aligned_dna_short_read'),
  ('aligned' , 'table_name' , 'aligned_rna_short_read'),
  ('aligned' , 'table_name' , 'aligned_nanopore'),
  ('aligned' , 'table_name' , 'aligned_pac_bio'),
  ('aligned' , 'table_name' , 'aligned_atac_short_read'),
  ('aligned' , 'table_name' , 'aligned_molecules_optical_mapping'),
  ('aligned' , 'table_name' , 'aligned_iclr'),
  ('experiment_dna_short_read' , 'experiment_type' , 'targeted'),
  ('experiment_dna_short_read' , 'experiment_type' , 'genome'),
  ('experiment_dna_short_read' , 'experiment_type' , 'exome'),
  ('aligned_dna_short_read' , 'reference_assembly' , 'GRCh38'),
  ('aligned_dna_short_read' , 'reference_assembly' , 'GRCh37'),
  ('aligned_dna_short_read' , 'reference_assembly' , 'NCBI36'),
  ('aligned_dna_short_read' , 'reference_assembly' , 'NCBI35'),
  ('aligned_dna_short_read' , 'reference_assembly' , 'NCBI34'),
  ('called_variants_dna_short_read' , 'variant_types' , 'SNV'),
  ('called_variants_dna_short_read' , 'variant_types' , 'INDEL'),
  ('called_variants_dna_short_read' , 'variant_types' , 'SV'),
  ('called_variants_dna_short_read' , 'variant_types' , 'RE'),
  ('called_variants_dna_short_read' , 'chrom' , 'ALL'),
  ('called_variants_dna_short_read' , 'chrom' , '1'),
  ('called_variants_dna_short_read' , 'chrom' , '2'),
  ('called_variants_dna_short_read' , 'chrom' , '3'),
  ('called_variants_dna_short_read' , 'chrom' , '4'),
  ('called_variants_dna_short_read' , 'chrom' , '5'),
  ('called_variants_dna_short_read' , 'chrom' , '6'),
  ('called_variants_dna_short_read' , 'chrom' , '7'),
  ('called_variants_dna_short_read' , 'chrom' , '8'),
  ('called_variants_dna_short_read' , 'chrom' , '9'),
  ('called_variants_dna_short_read' , 'chrom' , '10'),
  ('called_variants_dna_short_read' , 'chrom' , '11'),
  ('called_variants_dna_short_read' , 'chrom' , '12'),
  ('called_variants_dna_short_read' , 'chrom' , '13'),
  ('called_variants_dna_short_read' , 'chrom' , '14'),
  ('called_variants_dna_short_read' , 'chrom' , '15'),
  ('called_variants_dna_short_read' , 'chrom' , '16'),
  ('called_variants_dna_short_read' , 'chrom' , '17'),
  ('called_variants_dna_short_read' , 'chrom' , '18'),
  ('called_variants_dna_short_read' , 'chrom' , '19'),
  ('called_variants_dna_short_read' , 'chrom' , '20'),
  ('called_variants_dna_short_read' , 'chrom' , '21'),
  ('called_variants_dna_short_read' , 'chrom' , '22'),
  ('called_variants_dna_short_read' , 'chrom' , 'X'),
  ('called_variants_dna_short_read' , 'chrom' , 'Y'),
  ('called_variants_dna_short_read' , 'chrom' , 'MT'),
  ('experiment_rna_short_read' , 'rna_sample_type' , 'GREGoR_sample'),
  ('experiment_rna_short_read' , 'rna_sample_type' , 'isogenic_cell_line'),
  ('experiment_rna_short_read' , 'library_prep_type' , 'stranded poly-A pulldown'),
  ('experiment_rna_short_read' , 'library_prep_type' , 'stranded total RNA'),
  ('experiment_rna_short_read' , 'library_prep_type' , 'rRNA depletion'),
  ('experiment_rna_short_read' , 'library_prep_type' , 'globin depletion'),
  ('experiment_rna_short_read' , 'library_prep_type' , 'custom'),
  ('experiment_rna_short_read' , 'experiment_type' , 'single-end'),
  ('experiment_rna_short_read' , 'experiment_type' , 'paired-end'),
  ('experiment_rna_short_read' , 'experiment_type' , 'targeted'),
  ('experiment_rna_short_read' , 'experiment_type' , 'untargeted'),
  ('experiment_rna_short_read' , 'single_or_paired_ends' , 'single-end'),
  ('experiment_rna_short_read' , 'single_or_paired_ends' , 'paired-end'),
  ('aligned_rna_short_read' , 'reference_assembly' , 'GRCh38'),
  ('aligned_rna_short_read' , 'reference_assembly' , 'GRCh37'),
  ('aligned_rna_short_read' , 'reference_assembly' , 'NCBI36'),
  ('aligned_rna_short_read' , 'reference_assembly' , 'NCBI35'),
  ('aligned_rna_short_read' , 'reference_assembly' , 'NCBI34'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_chr'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_all'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_pri'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_basic_chr'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_basic_all'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'gencode_basic_pri'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'lncRNA_annotation'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'polyA_feature_annotation'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'consensus_pseudogenes'),
  ('aligned_rna_short_read' , 'gene_annotation_details' , 'predicted_tRNA_genes'),
  ('readcounts_rna_short_read' , 'quantification_types' , 'gene'),
  ('readcounts_rna_short_read' , 'quantification_types' , 'exon'),
  ('readcounts_rna_short_read' , 'quantification_types' , 'transcript'),
  ('readcounts_rna_short_read' , 'quantification_unit' , 'TPM'),
  ('readcounts_rna_short_read' , 'quantification_unit' , 'raw'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'LSK109'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'LSK110'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'LSK111'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'Kit 14'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'Rapid'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'Rapid kit 14'),
  ('experiment_nanopore' , 'seq_library_prep_kit_method' , 'Unknown'),
  ('experiment_nanopore' , 'experiment_type' , 'targeted'),
  ('experiment_nanopore' , 'experiment_type' , 'genome'),
  ('experiment_nanopore' , 'experiment_type' , 'fiberseq-genome'),
  ('experiment_nanopore' , 'experiment_type' , 'fiberseq-targeted'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore PromethION 48'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore PromethION 24'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore PromethION P2'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore PromethION P2 Solo'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore MinION Mk1C'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore MinION Mk1B'),
  ('experiment_nanopore' , 'sequencing_platform' , 'Oxford Nanopore Flongle'),
  ('experiment_nanopore' , 'chemistry_type' , 'R9.4.1'),
  ('experiment_nanopore' , 'chemistry_type' , 'R10.4.1'),
  ('aligned_nanopore' , 'reference_assembly' , 'chm13'),
  ('aligned_nanopore' , 'reference_assembly' , 'GRCh38_noalt'),
  ('aligned_nanopore' , 'reference_assembly' , 'GRCh38'),
  ('aligned_nanopore' , 'reference_assembly' , 'GRCh37'),
  ('aligned_nanopore' , 'reference_assembly' , 'NCBI36'),
  ('aligned_nanopore' , 'reference_assembly' , 'NCBI35'),
  ('aligned_nanopore' , 'reference_assembly' , 'NCBI34'),
  ('called_variants_nanopore' , 'variant_types' , 'SNV'),
  ('called_variants_nanopore' , 'variant_types' , 'INDEL'),
  ('called_variants_nanopore' , 'variant_types' , 'SV'),
  ('called_variants_nanopore' , 'variant_types' , 'RE'),
  ('called_variants_nanopore' , 'chrom' , 'ALL'),
  ('called_variants_nanopore' , 'chrom' , '1'),
  ('called_variants_nanopore' , 'chrom' , '2'),
  ('called_variants_nanopore' , 'chrom' , '3'),
  ('called_variants_nanopore' , 'chrom' , '4'),
  ('called_variants_nanopore' , 'chrom' , '5'),
  ('called_variants_nanopore' , 'chrom' , '6'),
  ('called_variants_nanopore' , 'chrom' , '7'),
  ('called_variants_nanopore' , 'chrom' , '8'),
  ('called_variants_nanopore' , 'chrom' , '9'),
  ('called_variants_nanopore' , 'chrom' , '10'),
  ('called_variants_nanopore' , 'chrom' , '11'),
  ('called_variants_nanopore' , 'chrom' , '12'),
  ('called_variants_nanopore' , 'chrom' , '13'),
  ('called_variants_nanopore' , 'chrom' , '14'),
  ('called_variants_nanopore' , 'chrom' , '15'),
  ('called_variants_nanopore' , 'chrom' , '16'),
  ('called_variants_nanopore' , 'chrom' , '17'),
  ('called_variants_nanopore' , 'chrom' , '18'),
  ('called_variants_nanopore' , 'chrom' , '19'),
  ('called_variants_nanopore' , 'chrom' , '20'),
  ('called_variants_nanopore' , 'chrom' , '21'),
  ('called_variants_nanopore' , 'chrom' , '22'),
  ('called_variants_nanopore' , 'chrom' , 'X'),
  ('called_variants_nanopore' , 'chrom' , 'Y'),
  ('called_variants_nanopore' , 'chrom' , 'MT'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'SMRTbell prep kit 3.0'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'SMRTbell prep kit - Revio 1.0'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'HiFI express template prep kit 2.0'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'Kinnex Full-Length RNA kit'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'MAS-Seq for 10x Single Cell 3'' kit'),
  ('experiment_pac_bio' , 'seq_library_prep_kit_method' , 'Unknown'),
  ('experiment_pac_bio' , 'experiment_type' , 'targeted'),
  ('experiment_pac_bio' , 'experiment_type' , 'genome'),
  ('experiment_pac_bio' , 'experiment_type' , 'fiberseq-genome'),
  ('experiment_pac_bio' , 'experiment_type' , 'fiberseq-targeted'),
  ('experiment_pac_bio' , 'experiment_type' , 'isoseq'),
  ('experiment_pac_bio' , 'experiment_type' , 'masseq'),
  ('experiment_pac_bio' , 'sequencing_platform' , 'PacBio Revio'),
  ('experiment_pac_bio' , 'sequencing_platform' , 'PacBio Sequel IIe'),
  ('experiment_pac_bio' , 'sequencing_platform' , 'PacBio Sequel II'),
  ('experiment_pac_bio' , 'barcode_kit' , 'SMRTbell barcoded adapter plate 3.0'),
  ('experiment_pac_bio' , 'barcode_kit' , 'Barcoded M13 primer plate'),
  ('experiment_pac_bio' , 'barcode_kit' , 'Barcoded overhang adapter kit - 8A/8B'),
  ('experiment_pac_bio' , 'barcode_kit' , 'SMRTbell adapter index plate 96A'),
  ('experiment_pac_bio' , 'application_kit' , 'MAS-Seq for 10x Single Cell 3'' kit'),
  ('experiment_pac_bio' , 'application_kit' , 'Iso-Seq express oligo kit'),
  ('experiment_pac_bio' , 'application_kit' , 'SMRTbell gDNA amplification kit'),
  ('aligned_pac_bio' , 'reference_assembly' , 'chm13'),
  ('aligned_pac_bio' , 'reference_assembly' , 'GRCh38_noalt'),
  ('aligned_pac_bio' , 'reference_assembly' , 'GRCh38'),
  ('aligned_pac_bio' , 'reference_assembly' , 'GRCh37'),
  ('aligned_pac_bio' , 'reference_assembly' , 'NCBI36'),
  ('aligned_pac_bio' , 'reference_assembly' , 'NCBI35'),
  ('aligned_pac_bio' , 'reference_assembly' , 'NCBI34'),
  ('called_variants_pac_bio' , 'variant_types' , 'SNV'),
  ('called_variants_pac_bio' , 'variant_types' , 'INDEL'),
  ('called_variants_pac_bio' , 'variant_types' , 'SV'),
  ('called_variants_pac_bio' , 'variant_types' , 'RE'),
  ('called_variants_pac_bio' , 'chrom' , 'ALL'),
  ('called_variants_pac_bio' , 'chrom' , '1'),
  ('called_variants_pac_bio' , 'chrom' , '2'),
  ('called_variants_pac_bio' , 'chrom' , '3'),
  ('called_variants_pac_bio' , 'chrom' , '4'),
  ('called_variants_pac_bio' , 'chrom' , '5'),
  ('called_variants_pac_bio' , 'chrom' , '6'),
  ('called_variants_pac_bio' , 'chrom' , '7'),
  ('called_variants_pac_bio' , 'chrom' , '8'),
  ('called_variants_pac_bio' , 'chrom' , '9'),
  ('called_variants_pac_bio' , 'chrom' , '10'),
  ('called_variants_pac_bio' , 'chrom' , '11'),
  ('called_variants_pac_bio' , 'chrom' , '12'),
  ('called_variants_pac_bio' , 'chrom' , '13'),
  ('called_variants_pac_bio' , 'chrom' , '14'),
  ('called_variants_pac_bio' , 'chrom' , '15'),
  ('called_variants_pac_bio' , 'chrom' , '16'),
  ('called_variants_pac_bio' , 'chrom' , '17'),
  ('called_variants_pac_bio' , 'chrom' , '18'),
  ('called_variants_pac_bio' , 'chrom' , '19'),
  ('called_variants_pac_bio' , 'chrom' , '20'),
  ('called_variants_pac_bio' , 'chrom' , '21'),
  ('called_variants_pac_bio' , 'chrom' , '22'),
  ('called_variants_pac_bio' , 'chrom' , 'X'),
  ('called_variants_pac_bio' , 'chrom' , 'Y'),
  ('called_variants_pac_bio' , 'chrom' , 'MT'),
  ('experiment_atac_short_read' , 'experiment_type' , 'targeted'),
  ('experiment_atac_short_read' , 'experiment_type' , 'genome'),
  ('experiment_atac_short_read' , 'experiment_type' , 'exome'),
  ('aligned_atac_short_read' , 'reference_assembly' , 'GRCh38'),
  ('aligned_atac_short_read' , 'reference_assembly' , 'GRCh37'),
  ('aligned_atac_short_read' , 'reference_assembly' , 'NCBI36'),
  ('aligned_atac_short_read' , 'reference_assembly' , 'NCBI35'),
  ('aligned_atac_short_read' , 'reference_assembly' , 'NCBI34'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_chr'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_all'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_comprehensive_pri'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_basic_chr'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_basic_all'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'gencode_basic_pri'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'lncRNA_annotation'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'polyA_feature_annotation'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'consensus_pseudogenes'),
  ('aligned_atac_short_read' , 'gene_annotation_details' , 'predicted_tRNA_genes'),
  ('called_peaks_atac_short_read' , 'peak_set_type' , 'narrowPeak'),
  ('called_peaks_atac_short_read' , 'peak_set_type' , 'gappedPeak'),
  ('called_peaks_atac_short_read' , 'peak_set_type' , 'IDR'),
  ('allele_specific_atac_short_read' , 'peak_set_type' , 'narrowPeak'),
  ('allele_specific_atac_short_read' , 'peak_set_type' , 'gappedPeak'),
  ('allele_specific_atac_short_read' , 'peak_set_type' , 'IDR'),
  ('aligned_molecules_optical_mapping' , 'reference_assembly' , 'GRCh38'),
  ('aligned_molecules_optical_mapping' , 'reference_assembly' , 'GRCh37'),
  ('aligned_molecules_optical_mapping' , 'reference_assembly' , 'NCBI36'),
  ('aligned_molecules_optical_mapping' , 'reference_assembly' , 'NCBI35'),
  ('aligned_molecules_optical_mapping' , 'reference_assembly' , 'NCBI34'),
  ('aligned_assembly_optical_mapping' , 'reference_assembly' , 'GRCh38'),
  ('aligned_assembly_optical_mapping' , 'reference_assembly' , 'GRCh37'),
  ('aligned_assembly_optical_mapping' , 'reference_assembly' , 'NCBI36'),
  ('aligned_assembly_optical_mapping' , 'reference_assembly' , 'NCBI35'),
  ('aligned_assembly_optical_mapping' , 'reference_assembly' , 'NCBI34'),
  ('called_variants_optical_mapping' , 'chrom' , 'ALL'),
  ('called_variants_optical_mapping' , 'chrom' , '1'),
  ('called_variants_optical_mapping' , 'chrom' , '2'),
  ('called_variants_optical_mapping' , 'chrom' , '3'),
  ('called_variants_optical_mapping' , 'chrom' , '4'),
  ('called_variants_optical_mapping' , 'chrom' , '5'),
  ('called_variants_optical_mapping' , 'chrom' , '6'),
  ('called_variants_optical_mapping' , 'chrom' , '7'),
  ('called_variants_optical_mapping' , 'chrom' , '8'),
  ('called_variants_optical_mapping' , 'chrom' , '9'),
  ('called_variants_optical_mapping' , 'chrom' , '10'),
  ('called_variants_optical_mapping' , 'chrom' , '11'),
  ('called_variants_optical_mapping' , 'chrom' , '12'),
  ('called_variants_optical_mapping' , 'chrom' , '13'),
  ('called_variants_optical_mapping' , 'chrom' , '14'),
  ('called_variants_optical_mapping' , 'chrom' , '15'),
  ('called_variants_optical_mapping' , 'chrom' , '16'),
  ('called_variants_optical_mapping' , 'chrom' , '17'),
  ('called_variants_optical_mapping' , 'chrom' , '18'),
  ('called_variants_optical_mapping' , 'chrom' , '19'),
  ('called_variants_optical_mapping' , 'chrom' , '20'),
  ('called_variants_optical_mapping' , 'chrom' , '21'),
  ('called_variants_optical_mapping' , 'chrom' , '22'),
  ('called_variants_optical_mapping' , 'chrom' , 'X'),
  ('called_variants_optical_mapping' , 'chrom' , 'Y'),
  ('called_variants_optical_mapping' , 'chrom' , 'MT'),
  ('experiment_iclr' , 'experiment_type' , 'targeted'),
  ('experiment_iclr' , 'experiment_type' , 'genome'),
  ('aligned_iclr' , 'reference_assembly' , 'GRCh38'),
  ('aligned_iclr' , 'reference_assembly' , 'GRCh37'),
  ('aligned_iclr' , 'reference_assembly' , 'NCBI36'),
  ('aligned_iclr' , 'reference_assembly' , 'NCBI35'),
  ('aligned_iclr' , 'reference_assembly' , 'NCBI34'),
  ('called_variants_iclr' , 'variant_types' , 'SNV'),
  ('called_variants_iclr' , 'variant_types' , 'INDEL'),
  ('called_variants_iclr' , 'variant_types' , 'SV'),
  ('called_variants_iclr' , 'variant_types' , 'RE'),
  ('called_variants_iclr' , 'chrom' , 'ALL'),
  ('called_variants_iclr' , 'chrom' , '1'),
  ('called_variants_iclr' , 'chrom' , '2'),
  ('called_variants_iclr' , 'chrom' , '3'),
  ('called_variants_iclr' , 'chrom' , '4'),
  ('called_variants_iclr' , 'chrom' , '5'),
  ('called_variants_iclr' , 'chrom' , '6'),
  ('called_variants_iclr' , 'chrom' , '7'),
  ('called_variants_iclr' , 'chrom' , '8'),
  ('called_variants_iclr' , 'chrom' , '9'),
  ('called_variants_iclr' , 'chrom' , '10'),
  ('called_variants_iclr' , 'chrom' , '11'),
  ('called_variants_iclr' , 'chrom' , '12'),
  ('called_variants_iclr' , 'chrom' , '13'),
  ('called_variants_iclr' , 'chrom' , '14'),
  ('called_variants_iclr' , 'chrom' , '15'),
  ('called_variants_iclr' , 'chrom' , '16'),
  ('called_variants_iclr' , 'chrom' , '17'),
  ('called_variants_iclr' , 'chrom' , '18'),
  ('called_variants_iclr' , 'chrom' , '19'),
  ('called_variants_iclr' , 'chrom' , '20'),
  ('called_variants_iclr' , 'chrom' , '21'),
  ('called_variants_iclr' , 'chrom' , '22'),
  ('called_variants_iclr' , 'chrom' , 'X'),
  ('called_variants_iclr' , 'chrom' , 'Y'),
  ('called_variants_iclr' , 'chrom' , 'MT')
ON DUPLICATE KEY UPDATE `key_value` = VALUES(`key_value`);
